global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'sotp-monitor'

scrape_configs:
 - job_name: 'backend'
   scrape_interval: 15s
   static_configs:
     - targets: ['backend:8000']
